### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by jalsed** [freshplanet/ANE-ImagePicker#33]
I get an error when using the ane with air sdk 16. Could the binary be updated to work?

**Comment by wafj999** [comment]
I am having the same issue

**Comment by jalsed** [comment]
It would be great if someone would create a new 64-bit binary (who knows how to do it...)

**Comment by jsaade** [comment]
https://github.com/jsaade/ANE-ImagePicker

**Comment by jalsed** [comment]
Thanks! It works.
