### ISSUE TITLE
Cannot get image from Camera

### ISSUE THREAD

**Issue by IngweLand** [freshplanet/ANE-ImagePicker#39]
It seems that everything that is returned when shooting the image by camera is the path to temporary image file which does not already exists at the moment it is accessed in actionscript 3 code. This is true for android only. This is valid for feature/more-compression branch

**Comment by IngweLand** [comment]
I was wrong - incorrectly loaded the image. Closing.

**Comment by Formability** [comment]
Can you tell me how you achieved this?. I'm having the same issue.
